# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - bbwa

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - uses: expo/expo-github-action@v5
      with:
        expo-version: 4.x
        expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
        expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}

    - name: deploy web-build as a target
      run: |
        yarn
        expo build:web

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'bbwa'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b400a742c4ca4387ab3a1bf4b21ca630 }}
        package: .
